<?php

function th_newsletter_email_validate_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'th_newsletter_entityform_edit_form') {
    $form['#validate'][] = 'th_newsletter_email_validate_form';
    $form['#submit'][] = 'th_newsletter_email_validate_form_submit';
  }
}

function th_newsletter_email_validate_form($form, $form_state) {
  $query = new EntityFieldQuery();

  $item = field_get_items('entityform', $form_state['entityform'], 'field_th_email');
  $email = array_shift($item);
  $email = $email['email'];

  $query->entityCondition('entity_type', 'entityform')
    ->entityCondition('bundle', 'th_newsletter')
    ->entityCondition('deleted', 0, '=')
    ->fieldCondition('field_th_email', 'email', $email, '=')
    ->count();

    $result = $query->execute();
  if ($result){
    form_set_error('field_th_email', t('This email address is already submitted.'));
  }
}
