<?php

function th_issue_random_tid($_tid = NULL) {
  $tid = &drupal_static(__FUNCTION__);
  if ($_tid) {
    $tid = $_tid;
  }
  return $tid;
}

function th_issue_random_get_tids() {

  if (isset($_GET['issue'])) {
      return $_GET['issue'];
  }

  if ($tid = &drupal_static('th_issue_random_tid')) {
    return $tid;
  }

  if ($tids = cache_get('th_issue_random_tids', 'cache_field')) {
   $tids = $tids->data;
  }

  if (!$tids) {
    $tids = db_query("select distinct
    (field_data_field_issue.field_issue_tid)
from
    field_data_field_issue
left join
    field_data_field_th_question ON field_data_field_th_question.field_th_question_target_id = field_data_field_issue.entity_id
left join
    field_data_field_th_status ON field_data_field_th_status.entity_id = field_data_field_th_question.field_th_question_target_id
where
    field_data_field_th_question.bundle = 'video' and field_data_field_th_status.field_th_status_value = 1")->fetchCol();

    if (empty($tids)) {
      return;
    }

    cache_set('th_issue_random_tids', $tids, 'cache_field');
  }

  $tid = th_issue_random_tid($tids[rand(0, count($tids)-1)]);
  return $tid;
}

function th_issue_random_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if (isset($form['issue'])
      && isset($form_state['view']) && $form_state['view']->name = 'home_page_videos') {
      if ($default_tid = th_issue_random_get_tids()) {
        $form['issue']['#value'] = th_issue_random_get_tids();
      }
    }
  }
}
