<?php

function video_view_count_menu() {
  $items['video_view_count'] = array(
    'page callback' => 'video_view_count',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function video_view_count() {
  global $user;
  if (variable_get('statistics_count_content_views', 0)) {
    if (isset($_POST['nid'])) {
      db_merge('node_counter')
        ->key(array('nid' => $_POST['nid']))
        ->fields(array(
          'daycount' => 1,
          'totalcount' => 1,
          'timestamp' => REQUEST_TIME,
        ))
        ->expression('daycount', 'daycount + 1')
        ->expression('totalcount', 'totalcount + 1')
        ->execute();
    }
  }
  if (variable_get('statistics_enable_access_log', 0)) {
    include_once DRUPAL_ROOT . '/includes/unicode.inc';

    $node = node_load($_POST['nid']);
    db_insert('accesslog')
      ->fields(array(
        'title' => truncate_utf8($node->title, 255),
        'path' => truncate_utf8($node->path, 255),
        'url' => '',
        'hostname' => ip_address(),
        'uid' => $user->uid,
        'sid' => session_id(),
        'timer' => (int) timer_read('page'),
        'timestamp' => REQUEST_TIME,
      ))
      ->execute();
  }
}

function video_view_count_field_attach_view_alter(&$output, $context) {
  global $user;
  $field_name = 'field_th_video';

  if (isset($output[$field_name])) {
    $field = $output[$field_name];
    $entity = $context['entity'];
    $settings = array();
    foreach ($field as $prop => $val) {
      if (is_array($val) && isset($val['#file'])) {
        $file = $val['#file'];
        $service = file_uri_scheme($file->uri);
        $url = parse_url($file->uri);
        $id = substr($url['path'], 1);

        $settings[] = array(
          'nid' => $entity->nid,
          'id' => $id,
          'uid' => $user->uid,
          'service' => $service,
          'fid' => $file->fid,
          'counted' => 0,
        );
        drupal_add_js(array('video_view_count' => $settings), 'setting');
      }

      if (is_array($val) && isset($val['file'])) {
        $output[$field_name][$prop]['file']['#options']['enablejsapi'] = 1;
      }
    }
  }
}