<?php

function questions_block_block_info() {
  $block['questions_block'] = array(
    'info' => t('Ask a question'),
    'cache' => DRUPAL_NO_CACHE,
    'region' => 'sidebar_second',
    'status' => 1,
  );

  $block['questions_block_user'] = array(
    'info' => t('User questions as votes'),
    'cache' => DRUPAL_NO_CACHE,
    'region' => 'sidebar_second',
    'status' => 1,
  );

  return $block;
}

function questions_block_block_view($delta='') {

  $block = array();
  if ($delta == 'questions_block') {
    $block['subject'] = t('Ask a question');
    $block['content'] = questions_block_contents();
  }

  if ($delta == 'questions_block_user') {
    global $user;
    if ($user->uid) {
      $block['subject'] = '';
      $block['content'] = questions_block_contents_user();
    }

  }
  return $block;
}

function questions_block_contents_user() {
  global $user;

  $uid = $user->uid;

  $fid_like = 5;
  $fid_unlike = 6;

  $count_votes = db_query("select
    count(*)
   from
    {flagging}
   where
    {flagging}.uid = $uid and ({flagging}.fid = $fid_like or {flagging}.fid = $fid_unlike)")->fetchField();

  $count_questons = db_query("select
    count(*)
  from
    {node}
   where
    {node}.type = 'question' and {node}.uid = $uid")->fetchField();
  return "<p>$count_votes Votes<br> $count_questons Questons</p>";
}


function questions_block_contents() {
  global $user;
  $count_people = db_query("select count(distinct {node}.uid)
  from
    {node}
  where
    {node}.type = 'question' and
    {node}.uid not in (
    select
      {users_roles}.uid
    from
      {users_roles}
    where
      {users_roles}.rid = 3
    )")->fetchField();

  $count_qustions = db_query("select count(*)
  from
    {node}
  where
    {node}.type = 'question' and
    {node}.uid not in (
    select
      {users_roles}.uid
    from
      {users_roles}
    where
      {users_roles}.rid = 3
    )")->fetchField();

  $count_votes = db_query("select sum({flag_counts}.count)
  from
    {flag_counts}
  where
    {flag_counts}.fid = 5 or {flag_counts}.fid = 6")->fetchField();

  if ($user->uid) {
    return array('#markup' => "<p>$count_people people have<br>".
                              "submitted $count_qustions question<br>".
                              "and cast $count_votes votes.<br>".
                              '<b>But what do you<br>'.
                              'think?</b><br>'.
                              l('submit a question', 'node/add/question'). '<br>' .
                              l('view all', 'all-questions').
                              '</p>'
    );
  }
  else {
    return array('#markup' => "<p>".
                              "$count_qustions Questions submitted and<br>".
                              "$count_votes Votes casted!<br>".
                              l('submit a question', 'node/add/question'). '<br>' .
                              l('view all', 'all-questions').
                              '</p>'
    );
  }

}
