<?php
function th_content_create() {
  $node = new stdClass();
  $node->title = "Privacy and Use Policy";
  $node->type = "page";
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = 1;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;
  node_save($node);

  if (property_exists($node, 'nid')) {
    variable_set('th_privacy_page', 'node/' . $node->nid);
  }

  $node = new stdClass();
  $node->title = "About";
  $node->type = "page";
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = 1;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;
  node_save($node);

  if (property_exists($node, 'nid')) {
    variable_set('th_about_page', 'node/' . $node->nid);
  }


}