<?php

function th_blocks_block_info() {

  $blocks['th_block_search'] = array(
    'info' => t('Town hall: Search'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 1,
  );

  $blocks['th_block_social_links'] = array(
    'info' => t('Town hall: TH Social links (SideBar)'),
    'status' => 1,
  );

  $blocks['th_block_scroll_up_footer'] = array(
    'info' => t('Town hall: Top (Footer)'),
    'status' => 1,
  );

  $blocks['th_block_social_links_footer'] = array(
    'info' => t('Town hall: TH Social links (Footer)'),
    'status' => 1,
  );

  $blocks['th_block_share_this'] = array(
    'info' => t('Town hall: Share this'),
    'status' => 1,
  );

  $blocks['th_block_partners'] = array(
    'info' => t('Town hall: Partners'),
    'status' => 1,
    'pages' => '<front>' . PHP_EOL . 'home' . PHP_EOL . 'node/*' . PHP_EOL . 'thd_search' . PHP_EOL. 'ths_search' . PHP_EOL,
  );

//  $blocks['th_block_user_action'] = array(
//    'info' => t('Town hall: UserName'),
//    'status' => 1,
//  );

  return $blocks;
}

function th_blocks_block_view($delta = '') {
  global $user;
  $block = array();

  switch ($delta) {
    case 'th_block_search':
      $block['subject'] = '';
      $block['content'] = array('#markup' => th_blocks_content($delta));
      break;
    case 'th_block_social_links' :
      $block['subject'] = 'Connect with us';
      $block['content'] = array('#markup' => th_blocks_content($delta));
      break;
    case 'th_block_social_links_footer' :
      $block['subject'] = 'Connect with us';
      $block['content'] = array('#markup' => th_blocks_content($delta));
      break;
    case 'th_block_share_this' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => th_blocks_content($delta));
      break;
    case 'th_block_partners' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => th_blocks_content($delta));
      break;
    case 'th_block_scroll_up_footer' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => th_blocks_content($delta));
      break;
//    case 'th_block_user_action' :
//      if (isset($user) && $user->uid) {
//        $block['subject'] = '';
//        $block_content = '<div class="user-action-wrapper"><div class="user-action">';
//        $block_content .= "<a class=\"user-action-name\" href=\"/user/$user->uid\">$user->name</a><span> &brvbar;</span><a class=\"user-action-logout\" href=\"/user/logout\">logout</a>";
//        $block_content .= '</div></div>';
//        $block['content'] = array('#markup'=> $block_content);
//      }
//      break;
  }

  return $block;
}

function th_blocks_content($delta) {
  $block_content = variable_get($delta . '_content', false);

  $content['th_block_search'] = '<form action="/' . variable_get('th_search_settings') . '" method="get" id="search-block-form" accept-charset="UTF-8">' . PHP_EOL
                              . '<div>' . PHP_EOL
                              . '<div class="container-inline">'. PHP_EOL
                              . '<h2 class="element-invisible">Search form</h2>'. PHP_EOL
                              . '<div class="form-item form-type-textfield form-item-search-block-form">'. PHP_EOL
                              . '<label class="element-invisible" for="edit-search-block-form--2">Search </label>'. PHP_EOL
                              . '<input title="Enter the terms you wish to search for." type="text" id="edit-search-block-form--2" name="search_api_views_fulltext" value="" size="15" maxlength="128" class="form-text">'. PHP_EOL
                              . '</div>'. PHP_EOL
                              . '<div class="form-actions form-wrapper" id="edit-actions"><input type="submit" id="edit-submit" name="op" value="Search" class="form-submit"></div>'. PHP_EOL
                              . '</div>'. PHP_EOL
                              . '</div>'. PHP_EOL
                              . '</form>'. PHP_EOL;

  $content['th_block_social_links'] = '<ul>'. PHP_EOL
                                    . '<li><a href="http://facebook.com"><img src="/profiles/town_hall/themes/townhalltheme/images/facebook.gif" /></a></li>'. PHP_EOL
                                    . '<li><a href="http://twitter.com"><img src="/profiles/town_hall/themes/townhalltheme/images/twitter.gif" /></a></li>'. PHP_EOL
                                    . '<li><a href="http://plus.google.com"><img src="/profiles/town_hall/themes/townhalltheme/images/google.gif" /></a></li>'. PHP_EOL
                                    . '</ul>'. PHP_EOL;

  $content['th_block_social_links_footer'] = '<ul>'. PHP_EOL
                                           . '<li><a href="http://facebook.com"><img src="/profiles/town_hall/themes/townhalltheme/images/facebook.gif" /></a></li>'. PHP_EOL
                                           . '<li><a href="http://twitter.com"><img src="/profiles/town_hall/themes/townhalltheme/images/twitter.gif" /></a></li>'. PHP_EOL
                                           . '<li><a href="http://plus.google.com"><img src="/profiles/town_hall/themes/townhalltheme/images/google.gif" /></a></li>'. PHP_EOL
                                           . '</ul>' . PHP_EOL
                                           . '<a class="privacy_policy">Privacy and Use Policy</a>' . PHP_EOL;
  $content['th_block_scroll_up_footer'] = '<div id="scroll-top">' . PHP_EOL
                                 . '<img src="/profiles/town_hall/themes/townhalltheme/images/scroll.png" />' . PHP_EOL
                                 .'<p class="top_text">TOP</p>'. PHP_EOL
                                 .'</div>'. PHP_EOL;

  $content['th_block_share_this'] = '<script type="text/javascript">var switchTo5x=true;</script>' . PHP_EOL
                                  . '<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>'. PHP_EOL
                                  . '<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>'. PHP_EOL
                                  . '<script type="text/javascript">stLight.options({publisher: "9160ae91-7e75-469f-b016-f34585a86864", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>'. PHP_EOL
                                  . '<script>'. PHP_EOL
                                  . 'var options={ "publisher": "9160ae91-7e75-469f-b016-f34585a86864", "position": "right", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "googleplus"]}};'. PHP_EOL
                                  . 'var st_hover_widget = new sharethis.widgets.hoverbuttons(options);'. PHP_EOL
                                  . '</script>'. PHP_EOL;

  $content['th_block_partners'] = '<img src="" style="width:100%"/>' . PHP_EOL
                                . '<img src="" style="width:100%"/>'. PHP_EOL;

  if ($block_content){
    return $block_content;
  } elseif (isset($content[$delta])) {
    return $content[$delta];
  }
  return false;
}

function th_blocks_block_configure($delta = '') {
  if ($default_value = th_blocks_content($delta)) {
    $form[$delta] = array(
      '#type' => 'text_format',
      '#title' => t('Block content'),
      '#format' => variable_get($delta .'_content_format', 'full_html' ),
      '#default_value' => $default_value,
    );
    return $form;
  }
}

function th_blocks_block_save($delta = '', $edit = array()) {
  if (isset($edit[$delta]['value']) && isset($edit[$delta]['format'])) {
    variable_set($delta . '_content', $edit[$delta]['value']);
    variable_set($delta . '_content_format', $edit[$delta]['format']);
  }
}

function th_blocks_block_info_alter(&$blocks, $theme, $code_blocks) {

  if ($theme != 'townhalltheme') {
    return;
  }

  if (isset($blocks['views'])) {

    if (isset($blocks['views']['candidates_videos-block'])) {
      $blocks['views']['candidates_videos-block']['status'] = 1;
      $blocks['views']['candidates_videos-block']['region'] = 'content';
    }

    if (isset($blocks['views']['th_party_page_videos-block'])) {
      $blocks['views']['th_party_page_videos-block']['status'] = 1;
      $blocks['views']['th_party_page_videos-block']['region'] = 'content';
    }

    if (isset($blocks['views']['issues_videos-block'])) {
      $blocks['views']['issues_videos-block']['status'] = 1;
      $blocks['views']['issues_videos-block']['region'] = 'content';
    }

    if (isset($blocks['views']['all_questions_block-block'])) {
      $blocks['views']['all_questions_block-block']['status'] = 1;
      $blocks['views']['all_questions_block-block']['visibility'] = BLOCK_VISIBILITY_LISTED;
      $blocks['views']['all_questions_block-block']['region'] = 'sidebar_first';
      $blocks['views']['all_questions_block-block']['pages'] = 'all-questions' . PHP_EOL . 'all-questions/issue/*' . PHP_EOL;
    }

    if (isset($blocks['views']['th_ef_newsletter_signup-block'])) {
      $blocks['views']['th_ef_newsletter_signup-block']['status'] = 1;
      $blocks['views']['th_ef_newsletter_signup-block']['region'] = 'footer';
      $blocks['views']['th_ef_newsletter_signup-block']['wieght'] = 2;
    }
  }

  if (isset($blocks['user']) && isset($blocks['user']['login'])) {
    $blocks['user']['login']['status'] = 1;
    $blocks['user']['login']['region'] = 'sidebar_second';
  }

  if (isset($blocks['quicktabs']) && isset($blocks['quicktabs']['most_shared_watched_tabs'])) {
    $blocks['quicktabs']['most_shared_watched_tabs']['status'] = 1;
    $blocks['quicktabs']['most_shared_watched_tabs']['region'] = 'sidebar_second';
    $blocks['quicktabs']['most_shared_watched_tabs']['weight'] = -9;
  }

  if (isset($blocks['th_blocks'])) {

    if (isset($blocks['th_blocks']['th_block_search'])) {
      $blocks['th_blocks']['th_block_search']['region'] = 'header';
    }

    if (isset($blocks['th_blocks']['th_block_social_links'])) {
      $blocks['th_blocks']['th_block_social_links']['region'] = 'sidebar_second';
      $blocks['th_blocks']['th_block_social_links']['weight'] = -10;
    }

    if (isset($blocks['th_blocks']['th_block_scroll_up_footer'])) {
      $blocks['th_blocks']['th_block_scroll_up_footer']['region'] = 'footer';
      $blocks['th_blocks']['th_block_scroll_up_footer']['weight'] = -1;
    }

    if (isset($blocks['th_blocks']['th_block_social_links_footer'])) {
      $blocks['th_blocks']['th_block_social_links_footer']['region'] = 'footer';
      $blocks['th_blocks']['th_block_social_links_footer']['weight'] = 2;
    }

    if (isset($blocks['th_blocks']['th_block_share_this'])) {
      $blocks['th_blocks']['th_block_share_this']['region'] = 'header';
    }

    if (isset($blocks['th_blocks']['th_block_partners'])) {
      $blocks['th_blocks']['th_block_partners']['region'] = 'sidebar_second';
    }

    if (isset($blocks['th_blocks']['th_block_partners'])) {
      $blocks['th_blocks']['th_block_partners']['regions'] = 'sidebar_second';
    }
//    if (isset($blocks['th_blocks']['th_block_user_action'])) {
//      $blocks['th_blocks']['th_block_user_action']['region'] = 'header';
//      $blocks['th_blocks']['th_block_user_action']['weight'] = -10;
//    }
  }

  if (isset($blocks['th_questions_block'])) {
    if (isset($blocks['th_questions_block']['th_questions_block'])) {
      $blocks['th_questions_block']['th_questions_block']['region'] = 'sidebar_second';
      $blocks['th_questions_block']['th_questions_block']['weight'] = -8;
    }

    if (isset($blocks['th_questions_block']['th_questions_block_user'])) {
      $blocks['th_questions_block']['th_questions_block_user']['region'] = 'sidebar_first';
      $blocks['th_questions_block']['th_questions_block_user']['weight'] = -9;
    }
  }

  if (isset($blocks['th_main_menu'])) {
    $blocks['th_main_menu']['th_main_menu']['region'] = 'featured';
  }
}