<?php

function th_share_count_enable() {
  $field_name = 'th_share_count';
  $bundle_name = 'video';


  $field = field_info_field($field_name);
  $instance = field_info_instance('node', $field_name, $bundle_name);

  if (empty($field)) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'number_integer',
      'entity_types' => array('node'),
    );

    $field = field_create_field($field);
  }

  if(empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'node',
      'bundle' => $bundle_name,
      'label' => 'Share count',
      'widget' => array('type' => 'number_integer'),
      'settings' => array(),
      'display' => array(),
      'weight' => 99,
    );
    $instance = field_create_instance($instance);
  }
}

//function th_share_count_process_page(&$variables, $hook) {
//  drupal_add_js(array('th_share_count' => th_share_count_get_services()), 'setting');
//  drupal_add_js('http://wd.sharethis.com/button/buttons.js', 'external');
//  drupal_add_js(drupal_get_path('module','th_share_count') . '/th_share_count.js');
//
//  if (isset($variables['page']['content']['system_main']['nodes'])) {
//    $nodes = &$variables['page']['content']['system_main']['nodes'];
//
//    foreach($nodes as $nid => $node) {
//      if (isset($node['sharethis'])) {
//        $nodes[$nid]['sharethis']['#attributes']['nid'] = $nid;
//        $nodes[$nid]['sharethis']['#attributes']['path'] = th_share_count_get_node_path($node['#node']);
//      }
//    }
//
//  }
//}

function th_share_count_get_services() {
  $service_array = array();
  $service_option = variable_get('sharethis_service_option');
  foreach(explode(",", $service_option) as $service) {
    $service = explode(":", $service);

    if (count($service) < 2) {
      continue;
    }

    $service_array[] = substr($service[1], 0, -1);
  }
  return $service_array;
}

function th_share_count_get_node_path($node) {
  global $base_url;
  if (property_exists($node, 'path')) {
    $path = $node->path;
  }
  else {
    $path = "/node/" . $node->nid;
  }
  if (module_exists('pathauto')) {
    $path = '/' . drupal_lookup_path('alias',"node/" . $node->nid);
  }
  return $base_url . $path;
}

function th_share_count_menu() {
  $items['th_share_count_get_count/%/%']= array(
    'title' => 'Share This post request',
    'page callback' => 'th_share_count_count',
    'page arguments' => array(1, 2),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  $items['th_share_count_get_count']= array(
    'title' => 'Share This post request',
    'page callback' => 'th_share_count_count',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function th_share_count_count($nid = NULL, $request = NULL) {
  $url  = $_POST['url'];
  $nid = isset($_POST['nid']) ? $_POST['nid'] : $nid;

  if (empty($url) && empty($nid)) {
    return drupal_not_found();
  }

  $request = array(
    'path' => 'http://rest.sharethis.com/reach/getUrlInfo.php?',
    'pub_key' => 'pub_key=9160ae91-7e75-469f-b016-f34585a86864',
    'acces_key' => 'access_key=ff0d0e779f445ac74344c2d751162fee',
    'url' => 'url=' . $url,
  );

  $request = implode("&", $request);
  $services = th_share_count_get_services();
  $counters = array();
  foreach($services as $service) {
    $result = drupal_http_request($request . '&provider=' . $service);
    if (!empty($result->data)) {
      $data_array = drupal_json_decode($result->data);
      $counters[$service] = $data_array[$service];
    }

  }
  if (is_null($nid)) {

    $url = parse_url($url);
    $path = substr($url['path'], 1);
    $_path = drupal_lookup_path("source", $path) ;
    $path = $_path ? $_path : $path;
    $node = menu_get_object("node", 1, $path);
  }
  else {
    $node = node_load($nid);
  }

  if (isset($node) && property_exists($node, 'th_share_count')) {
    $th_share_count = 0;
    foreach ($counters as $service) {
      $th_share_count += (int)$service['inbound'];
    }

    $node->th_share_count[$node->language][0]['value'] = $th_share_count;
    node_save($node);
  }

  drupal_json_output($counters);
}

function th_share_count_preprocess_html_tag(&$tag) {
  if (isset($tag['element']['#attributes']) && isset($tag['element']['#attributes']['st_url'])) {
    drupal_add_js('http://wd.sharethis.com/button/buttons.js', 'external');
    drupal_add_js(drupal_get_path('module','th_share_count') . '/th_share_count.js');
    $tag['element']['#attributes']['class'] .= ' th_share_count';
  }
}
