<?php

function town_hall_blocks_block_info() {

  $blocks['th_block_search'] = array(
    'info' => t('Town hall: Search'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 1,
    'region' => 'header',
  );

  $blocks['th_block_social_links'] = array(
    'info' => t('Town hall: TH Social links (Footer)'),
    'status' => 1,
    'region' => 'sidebar_second',
  );

  $blocks['th_block_social_links_footer'] = array(
    'info' => t('Town hall: TH Social links (Footer)'),
    'status' => 1,
    'region' => 'footer',
  );

  $blocks['th_block_share_this'] = array(
    'info' => t('Town hall: Share this'),
    'status' => 1,
    'region' => 'header',
  );

  $blocks['th_block_partners'] = array(
    'info' => t('Town hall: Partners'),
    'status' => 1,
    'region' => 'sidebar_second',
    'pages' => '<front>' . PHP_EOL . 'home' . PHP_EOL . 'node/*' . PHP_EOL . 'thd_search' . PHP_EOL. 'ths_search' . PHP_EOL,
  );

  return $blocks;
}

function town_hall_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'th_block_search':
      $block['subject'] = '';
      $block['content'] = array('#markup' => town_hall_blocks_content($delta));
      break;
    case 'th_block_social_links' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => town_hall_blocks_content($delta));
      break;
    case 'th_block_social_links_footer' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => town_hall_blocks_content($delta));
      break;
    case 'th_block_share_this' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => town_hall_blocks_content($delta));
      break;
    case 'th_block_partners' :
      $block['subject'] = '';
      $block['content'] = array('#markup' => town_hall_blocks_content($delta));
  }

  return $block;
}

function town_hall_blocks_content($delta) {
  $block_content = variable_get($delta . '_content');

  $content['th_block_search'] = '<form action="/' . variable_get('th_search_settings') . '" method="get" id="search-block-form" accept-charset="UTF-8">' . PHP_EOL
                              . '<div>' . PHP_EOL
                              . '<div class="container-inline">'. PHP_EOL
                              . '<h2 class="element-invisible">Search form</h2>'. PHP_EOL
                              . '<div class="form-item form-type-textfield form-item-search-block-form">'. PHP_EOL
                              . '<label class="element-invisible" for="edit-search-block-form--2">Search </label>'. PHP_EOL
                              . '<input title="Enter the terms you wish to search for." type="text" id="edit-search-block-form--2" name="search_api_views_fulltext" value="" size="15" maxlength="128" class="form-text">'. PHP_EOL
                              . '</div>'. PHP_EOL
                              . '<div class="form-actions form-wrapper" id="edit-actions"><input type="submit" id="edit-submit" name="op" value="Search" class="form-submit"></div>'. PHP_EOL
                              . '</div>'. PHP_EOL
                              . '</div>'. PHP_EOL
                              . '</form>'. PHP_EOL;

  $content['th_block_social_links'] = '<ul>'. PHP_EOL
                                    . '<li><a href="http://facebook.com">Facebook</a></li>'. PHP_EOL
                                    . '<li><a href="http://twitter.com">Twitter</a></li>'. PHP_EOL
                                    . '<li><a href="http://plus.google.com">Google+</a></li>'. PHP_EOL
                                    . '</ul>'. PHP_EOL;

  $content['th_block_social_links_footer'] = '<ul>'. PHP_EOL
                                           . '<li><a href="http://facebook.com">Facebook</a></li>'. PHP_EOL
                                           . '<li><a href="http://twitter.com">Twitter</a></li>'. PHP_EOL
                                           . '<li><a href="http://plus.google.com">Google+</a></li>'. PHP_EOL
                                           . '</ul>'. PHP_EOL;

  $content['th_block_share_this'] = '<script type="text/javascript">var switchTo5x=true;</script>' . PHP_EOL
                                  . '<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>'. PHP_EOL
                                  . '<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>'. PHP_EOL
                                  . '<script type="text/javascript">stLight.options({publisher: "9160ae91-7e75-469f-b016-f34585a86864", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>'. PHP_EOL
                                  . '<script>'. PHP_EOL
                                  . 'var options={ "publisher": "9160ae91-7e75-469f-b016-f34585a86864", "position": "right", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "googleplus"]}};'. PHP_EOL
                                  . 'var st_hover_widget = new sharethis.widgets.hoverbuttons(options);'. PHP_EOL
                                  . '</script>'. PHP_EOL;

  $content['th_block_partners'] = '<img src="" style="width:100%"/>' . PHP_EOL
                                . '<img src="" style="width:100%"/>'. PHP_EOL;

  return $block_content ? $block_content : isset($content[$delta]) ? $content[$delta] : NULL;
}

function town_hall_blocks_block_configure($delta = '') {

  $form[$delta] = array(
    '#type' => 'text_format',
    '#title' => t('Block content'),
    '#format' => variable_get($delta .'format', 'full_html' ),
    '#default_value' => town_hall_blocks_content($delta),
  );

  return $form;
}

function town_hall_blocks_block_save($delta = '', $edit = array()) {
  if (isset($edit[$delta]['values']) && isset($edit[$delta]['format'])) {
    variable_set($delta . '_content', $edit[$delta]['values']);
    variable_set($delta . '_content', $edit[$delta]['format']);
  }
}

function town_hall_blocks_block_info_alter(&$blocks, $theme, $code_blocks) {
  if (isset($blocks['views'])) {

    if (isset($blocks['views']['candidates_videos-block'])) {
      $blocks['views']['candidates_videos-block']['status'] = 1;
      $blocks['views']['candidates_videos-block']['region'] = 'content';
    }

    if (isset($blocks['views']['th_party_page_videos-block'])) {
      $blocks['views']['th_party_page_videos-block']['status'] = 1;
      $blocks['views']['th_party_page_videos-block']['region'] = 'content';
    }

    if (isset($blocks['views']['issues_videos-block'])) {
      $blocks['views']['issues_videos-block']['status'] = 1;
      $blocks['views']['issues_videos-block']['region'] = 'content';
    }
  }
}
