<?php
function town_hall_config_menu() {

  $items['admin/config/town_hall_config'] = array(
    'title' => 'Town Hall config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('town_hall_config_form'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

function town_hall_config_form($form, &$form_state) {
  $form = system_settings_form($form);

  $form['#submit'][] = 'town_hall_config_form_submit';
  $default_search = variable_get('th_search_settings');
    $form['th_search_settings'] = array (
    '#type' => 'select',
    '#title' => "Search options",
    '#description' => 'By default, "Database" index is enabled. If you have Apache Solr , please enable "Apache Solr"',
    '#options' => array(
      'thd_search' => t('Database'),
      'ths_search' => t('Apache Solr'),
    ),
    '#default_value' => $default_search ? $default_search : '',
  );
  $form['th_permission_mode'] = array(
    '#type' => 'select',
    '#title' => "Permission mode",
    '#description' => "Site Permissions",
    '#options' => array(
      0 => t('Registration required'),
      1 => t('Anonymous'),
    ),
  );

  return $form;
}

function town_hall_config_form_submit($form, &$form_state) {

  if ($form_state['values']['th_search_settings'] == 'thd_search') {
    if (module_exists('th_search_solr2')) {
      module_disable(array('th_search_solr2'));
    }
    module_enable(array('th_search_db'));
    db_query("UPDATE {system} SET weight = 99 WHERE name = 'th_search_db'");
  }
  else if ($form_state['values']['th_search_settings'] == 'ths_search') {
    if (module_exists('th_search_db')) {
      module_disable(array('th_search_db'));
    }
    module_enable(array('th_search_solr2'));
    db_query("UPDATE {system} SET weight = 99 WHERE name = 'th_search_solr2'");
  }

  drupal_flush_all_caches();
}